### ISSUE TITLE
Setting password

### ISSUE THREAD

**Issue by rgr-1** [mirofromdiro/JK-firmware-code#1]
The settings password for JK-BMS can be constructed as:
"your time dependent code"+"crc8.ROHC(serilar of inverter)" 

With this I am able to "unlock" settings of both mine jk-bms PB2A16S20P..
Sure anyone else who may connect to them will be able as well. I will not bother you with my ranting about "JK security" or rather absence of it :)

You may add this to your code generator to save people from unnecessary interaction with JK. 
    

Below is the js code I played with in Node-Red:

```
// it uses easy-crc from https://github.com/emn178/js-crc

let byte_array = [
    0x01, 0x04, 0x03, 0x02, 0x08, 0x06, 0x07, 0x05,
    0x04, 0x01, 0x03, 0x02, 0x05, 0x08, 0x07, 0x06,
    0x08, 0x02, 0x01, 0x03, 0x05, 0x04, 0x07, 0x06,
    0x06, 0x02, 0x03, 0x04, 0x01, 0x07, 0x05, 0x08,
    0x07, 0x01, 0x02, 0x03, 0x05, 0x06, 0x04, 0x08,
    0x05, 0x02, 0x03, 0x04, 0x01, 0x08, 0x07, 0x06,
    0x02, 0x03, 0x04, 0x01, 0x05, 0x08, 0x06, 0x07,
    0x03, 0x04, 0x01, 0x02, 0x07, 0x08, 0x05, 0x06,
    0x05, 0x06, 0x01, 0x02, 0x07, 0x08, 0x03, 0x04,
    0x06, 0x07, 0x01, 0x02, 0x05, 0x08, 0x03, 0x04
];

// ---------------------
//let d = new Date("2024-06-06T08:00:00")
let d = new Date()

//let serial = '40110490041'
let serial = '40110490823'

let code = getCode(d)
let pswd_addon = getPasswordPart(serial)

// settings password = "force code" + "crc8.rohc from serial"
let res = {
    "code": code,
    "pswd": code + pswd_addon 
}

msg.payload = res
return msg;

// Test case 1: 
// time: 2024.06.06_08:25:00  -> 24060606
// serial: 40110490041
// code: 02400666
// pssw: 0240066635
//
// Test case 2:
// serial: 40110490823
// pswd_addon: 3c
//

function getPasswordPart(serial) {
    let checksum = easyCrc.crc8('ROHC', serial);
    let s = checksum.toString(16)
    return s
}

function getCode(date_time = new Date()) {
    var d = date_time.toISOString().slice(2, 10).replace(/-/g, "") + date_time.getUTCHours().toString().padStart(2, '0');
    var qs = d.split('').reduce((a, b) => a + parseInt(b), 0);
    var m = qs % 10;
    var r = "";
    for (var i = 0; i < 8; i++) {
        var index = i + m * 8;
        var c = byte_array[index];
        r += d[c - 1];
    }
    return r;
}
```

**Comment by mirofromdiro** [comment]
Thanks for the good work!
I added the settings password calculation in commit 686da23.

Could you please test?

**Comment by rgr-1** [comment]
Works perfectly with mine 2 JK-BMSs
The only comment - maybe it make sense to add "This code is valid for XXm YYs" sentence to this as well.

Or maybe make it similar to what I got from jk..  which triggered me to have a closer look on it :) 

![image](https://github.com/mirofromdiro/JK-firmware-code/assets/72152978/c75a0810-4f60-47de-844e-c24fdbc37583)
![image](https://github.com/mirofromdiro/JK-firmware-code/assets/72152978/8f529fa4-c853-49d0-a885-b869a47acb61)
